### ISSUE TITLE
Crash in PowerToys

### ISSUE THREAD

**Issue by pilgrimlyieu** [hlaueriksson/GEmojiSharp#23]
Hello, I met an issue recently. When I use <kbd>Alt</kbd> + <kbd>Space</kbd> to open the Run window, type something like `emoji laugh`, select one of emojis and press <kbd>Enter</kbd> or <kbd>Ctrl</kbd> + <kbd>C</kbd>, an error will be thrown like below.

The version of GEmojiSharp is 3.1.0, latest in release. The version of PowerToys is 0.74.0, also the latest.

```
Version: 0.74.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
Date: 2023/10/03 11:01:59
Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at GEmojiSharp.PowerToysRun.Main.CopyToClipboard(String value)
   at GEmojiSharp.PowerToysRun.Main.<>c__DisplayClass16_3.<Query>b__6(ActionContext _)
   at PowerLauncher.ViewModel.MainViewModel.<>c__DisplayClass30_0.<OpenResultsEvent>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at PowerLauncher.ViewModel.MainViewModel.OpenResultsEvent(Object index, Boolean isMouseClick)
   at PowerLauncher.ViewModel.MainViewModel.<InitializeKeyCommands>b__31_10(Object index)
   at PowerLauncher.ViewModel.RelayCommand.Execute(Object parameter)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Since other Run plugin works normal, I'm wondering that if I've done something wrong on this plugin or I've missed something. I couldn't find similar cases and solution in internet so I open an issue for help.

If I've done something wrong, please inform me! Thanks for your wonderful plugin!

**Comment by hlaueriksson** [comment]
@pilgrimlyieu thanks for reporting this issue!

Maybe I need to access the clipboard from a new thread, like the [UnitConverter](https://github.com/microsoft/PowerToys/blob/b41dd81177c98a3a71402b280bc72da68deffb05/src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/Main.cs#L72-L86) plugin.

Can you give examples of out of the box plugins where copy to clipboard works?

**Comment by pilgrimlyieu** [comment]
> Can you give examples of out of the box plugins where copy to clipboard works?

[PowerTranslator](https://github.com/N0I0C0K/PowerTranslator) & [EverythingPowerToys](https://github.com/lin-ycv/EverythingPowerToys) seem to work.

---

Although the crash will occur, the emoji could still be copied to clipboard correctly.

**Comment by pilgrimlyieu** [comment]
> Can you give examples of out of the box plugins where copy to clipboard works?
 [PowerTranslator](https://github.com/N0I0C0K/PowerTranslator) seems to work.

**Comment by hlaueriksson** [comment]
So both [PowerTranslator](https://github.com/N0I0C0K/PowerTranslator/blob/c4744a215b7bbfefc0211ddb4b63e82a307a37cd/src/Utils.cs#L46) and [EverythingPowerToys](https://github.com/lin-ycv/EverythingPowerToys/blob/2796144b78fc78d9b4929021be295545e1e1dfef/ContextMenuLoader.cs#L174) use `Clipboard.SetDataObject` instead of `Clipboard.SetText`.

I will make this change in `GEmojiSharp.PowerToysRun` when I get the time.
Or if you want to contribute, please submit a PR.

**Comment by pilgrimlyieu** [comment]
> I will make this change in `GEmojiSharp.PowerToysRun` when I get the time. Or if you want to contribute, please submit a PR.

I would like to but I'm a student learning C at first and I have no idea with C#. I can wait and keep this issue opened until you get the time. Or if the change is minor, could you so please give me some guidance?

I opened a PR in #24.

**Comment by hlaueriksson** [comment]
@pilgrimlyieu thanks for the PR! I'll create a new release with the fix included.

**Comment by hlaueriksson** [comment]
You can try out your fix in version `3.1.1` of `GEmojiSharp.PowerToysRun`

Download and install; https://github.com/hlaueriksson/GEmojiSharp/releases/tag/v3.1.1

**Comment by pilgrimlyieu** [comment]
Works normally now. Thanks for your awesome plugin!

Should I close this issue now?

**Comment by hlaueriksson** [comment]
That's great to hear that it works. Thanks for your contribution to the project!
